export const AUTH_USER = 'AUTH_USER';
export const SIGNOUT = 'SIGNOUT';
export const FETCH_USER = 'FETCH_USER';
export const UPDATE_AUTH_TOKEN = 'UPDATE_AUTH_TOKEN';
export const UPDATE_AUTH_USER_INFO = 'UPDATE_AUTH_USER_INFO';
export const UPDATE_AUTH_USER_COVER_PICTURE = 'UPDATE_AUTH_USER_COVER_PICTURE';
export const UPDATE_AUTH_USER_PROFILE_PICTURE =
  'UPDATE_AUTH_USER_PROFILE_PICTURE';
